export interface FoodItem {
  id: string;
  name: string;
  categoryId: string;
  image: any;
}

export const FOOD_LIST: FoodItem[] = [
  {
    id: "1",
    name: "Banana Bread",
    categoryId: "6",
    image: require("@/assets/images/foods/bakery/Banana Bread.png"),
  },
  {
    id: "2",
    name: "Blueberry Muffin",
    categoryId: "6",
    image: require("@/assets/images/foods/bakery/Blueberry Muffin.png"),
  },
  {
    id: "3",
    name: "Brownie",
    categoryId: "6",
    image: require("@/assets/images/foods/bakery/Brownie.png"),
  },
  {
    id: "4",
    name: "Cheesecake",
    categoryId: "6",
    image: require("@/assets/images/foods/bakery/Cheesecake.png"),
  },
  {
    id: "5",
    name: "Chocolate Chip Cookies",
    categoryId: "6",
    image: require("@/assets/images/foods/bakery/Chocolate Chip Cookies.png"),
  },
  {
    id: "6",
    name: "Cinnamon Roll",
    categoryId: "6",
    image: require("@/assets/images/foods/bakery/Cinnamon Roll.png"),
  },
  {
    id: "7",
    name: "Croissant",
    categoryId: "6",
    image: require("@/assets/images/foods/bakery/Croissant.png"),
  },
  {
    id: "8",
    name: "Egg Tart",
    categoryId: "6",
    image: require("@/assets/images/foods/bakery/Egg Tart.png"),
  },
  {
    id: "9",
    name: "Fruit Danish",
    categoryId: "6",
    image: require("@/assets/images/foods/bakery/Fruit Danish.png"),
  },
  {
    id: "10",
    name: "Sourdough Bread",
    categoryId: "6",
    image: require("@/assets/images/foods/bakery/Sourdough Bread.png"),
  },
  {
    id: "11",
    name: "Bananas in Coconut Milk",
    categoryId: "3",
    image: require("@/assets/images/foods/desserts/Bananas in Coconut Milk.png"),
  },
  {
    id: "12",
    name: "Bua Loy with Sweet Egg",
    categoryId: "3",
    image: require("@/assets/images/foods/desserts/Bua Loy with Sweet Egg.png"),
  },
  {
    id: "13",
    name: "Coconut Milk Ice Cream",
    categoryId: "3",
    image: require("@/assets/images/foods/desserts/Coconut Milk Ice Cream.png"),
  },
  {
    id: "14",
    name: "Grass Jelly with Fresh Milk",
    categoryId: "3",
    image: require("@/assets/images/foods/desserts/Grass Jelly with Fresh Milk.png"),
  },
  {
    id: "15",
    name: "Lod Chong in Coconut Milk",
    categoryId: "3",
    image: require("@/assets/images/foods/desserts/Lod Chong in Coconut Milk.png"),
  },
  {
    id: "16",
    name: "Mango Sticky Rice",
    categoryId: "3",
    image: require("@/assets/images/foods/desserts/Mango Sticky Rice.png"),
  },
  {
    id: "17",
    name: "Pumpkin Custard",
    categoryId: "3",
    image: require("@/assets/images/foods/desserts/Pumpkin Custard.png"),
  },
  {
    id: "18",
    name: "Red Rubies in Coconut Milk",
    categoryId: "3",
    image: require("@/assets/images/foods/desserts/Red Rubies in Coconut Milk.png"),
  },
  {
    id: "19",
    name: "Sticky Rice with Custard",
    categoryId: "3",
    image: require("@/assets/images/foods/desserts/Sticky Rice with Custard.png"),
  },
  {
    id: "20",
    name: "Thai Coconut Pudding",
    categoryId: "3",
    image: require("@/assets/images/foods/desserts/Thai Coconut Pudding.png"),
  },
  {
    id: "21",
    name: "Coconut Water",
    categoryId: "4",
    image: require("@/assets/images/foods/drinks/Coconut Water.png"),
  },
  {
    id: "22",
    name: "Fresh Orange Juice",
    categoryId: "4",
    image: require("@/assets/images/foods/drinks/Fresh Orange Juice.png"),
  },
  {
    id: "23",
    name: "Honey Lime Soda",
    categoryId: "4",
    image: require("@/assets/images/foods/drinks/Honey Lime Soda.png"),
  },
  {
    id: "24",
    name: "Iced Cocoa",
    categoryId: "4",
    image: require("@/assets/images/foods/drinks/Iced Cocoa.png"),
  },
  {
    id: "25",
    name: "Iced Coffee",
    categoryId: "4",
    image: require("@/assets/images/foods/drinks/Iced Coffee.png"),
  },
  {
    id: "26",
    name: "Lemon Iced Tea",
    categoryId: "4",
    image: require("@/assets/images/foods/drinks/Lemon Iced Tea.png"),
  },
  {
    id: "27",
    name: "Matcha Latte",
    categoryId: "4",
    image: require("@/assets/images/foods/drinks/Matcha Latte.png"),
  },
  {
    id: "28",
    name: "Pink Milk",
    categoryId: "4",
    image: require("@/assets/images/foods/drinks/Pink Milk.png"),
  },
  {
    id: "29",
    name: "Thai Tea",
    categoryId: "4",
    image: require("@/assets/images/foods/drinks/Thai Tea.png"),
  },
  {
    id: "30",
    name: "Watermelon Smoothie",
    categoryId: "4",
    image: require("@/assets/images/foods/drinks/Watermelon Smoothie.png"),
  },
  {
    id: "31",
    name: "Avocado Toast with Boiled Egg",
    categoryId: "10",
    image: require("@/assets/images/foods/healthy/Avocado Toast with Boiled Egg.png"),
  },
  {
    id: "32",
    name: "Brown Rice with Grilled Salmon",
    categoryId: "10",
    image: require("@/assets/images/foods/healthy/Brown Rice with Grilled Salmon.png"),
  },
  {
    id: "33",
    name: "Chicken Breast Salad",
    categoryId: "10",
    image: require("@/assets/images/foods/healthy/Chicken Breast Salad.png"),
  },
  {
    id: "34",
    name: "Chicken Breast and Mixed Vegetable Wrap",
    categoryId: "10",
    image: require("@/assets/images/foods/healthy/Chicken Breast and Mixed Vegetable Wrap.png"),
  },
  {
    id: "35",
    name: "Chicken Quinoa Bowl",
    categoryId: "10",
    image: require("@/assets/images/foods/healthy/Chicken Quinoa Bowl.png"),
  },
  {
    id: "36",
    name: "Fruit Oatmeal",
    categoryId: "10",
    image: require("@/assets/images/foods/healthy/Fruit Oatmeal.png"),
  },
  {
    id: "37",
    name: "Steamed Fish with Vegetables",
    categoryId: "10",
    image: require("@/assets/images/foods/healthy/Steamed Fish with Vegetables.png"),
  },
  {
    id: "38",
    name: "Tofu Poke Bowl",
    categoryId: "10",
    image: require("@/assets/images/foods/healthy/Tofu Poke Bowl.png"),
  },
  {
    id: "39",
    name: "Whole Wheat Tuna Sandwich",
    categoryId: "10",
    image: require("@/assets/images/foods/healthy/Whole Wheat Tuna Sandwich.png"),
  },
  {
    id: "40",
    name: "Yogurt with Granola and Fruit",
    categoryId: "10",
    image: require("@/assets/images/foods/healthy/Yogurt with Granola and Fruit.png"),
  },
  {
    id: "41",
    name: "Bibimbap",
    categoryId: "9",
    image: require("@/assets/images/foods/international/Bibimbap.png"),
  },
  {
    id: "42",
    name: "Butter Chicken",
    categoryId: "9",
    image: require("@/assets/images/foods/international/Butter Chicken.png"),
  },
  {
    id: "43",
    name: "Cheeseburger",
    categoryId: "9",
    image: require("@/assets/images/foods/international/Cheeseburger.png"),
  },
  {
    id: "44",
    name: "Fish and Chips",
    categoryId: "9",
    image: require("@/assets/images/foods/international/Fish and Chips.png"),
  },
  {
    id: "45",
    name: "Margherita Pizza",
    categoryId: "9",
    image: require("@/assets/images/foods/international/Margherita Pizza.png"),
  },
  {
    id: "46",
    name: "Pho",
    categoryId: "9",
    image: require("@/assets/images/foods/international/Pho.png"),
  },
  {
    id: "47",
    name: "Ramen",
    categoryId: "9",
    image: require("@/assets/images/foods/international/Ramen.png"),
  },
  {
    id: "48",
    name: "Salmon Sushi",
    categoryId: "9",
    image: require("@/assets/images/foods/international/Salmon Sushi.png"),
  },
  {
    id: "49",
    name: "Spaghetti Carbonara",
    categoryId: "9",
    image: require("@/assets/images/foods/international/Spaghetti Carbonara.png"),
  },
  {
    id: "50",
    name: "Tacos",
    categoryId: "9",
    image: require("@/assets/images/foods/international/Tacos.png"),
  },
  {
    id: "51",
    name: "Bacon",
    categoryId: "5",
    image: require("@/assets/images/foods/meat/Bacon.png"),
  },
  {
    id: "52",
    name: "Beef",
    categoryId: "5",
    image: require("@/assets/images/foods/meat/Beef.png"),
  },
  {
    id: "53",
    name: "Chicken Breast",
    categoryId: "5",
    image: require("@/assets/images/foods/meat/Chicken Breast.png"),
  },
  {
    id: "54",
    name: "Chicken Thigh",
    categoryId: "5",
    image: require("@/assets/images/foods/meat/Chicken Thigh.png"),
  },
  {
    id: "55",
    name: "Chicken Wings",
    categoryId: "5",
    image: require("@/assets/images/foods/meat/Chicken Wings.png"),
  },
  {
    id: "56",
    name: "Clams",
    categoryId: "5",
    image: require("@/assets/images/foods/meat/Clams.png"),
  },
  {
    id: "57",
    name: "Crab",
    categoryId: "5",
    image: require("@/assets/images/foods/meat/Crab.png"),
  },
  {
    id: "58",
    name: "Crispy Pork",
    categoryId: "5",
    image: require("@/assets/images/foods/meat/Crispy Pork.png"),
  },
  {
    id: "59",
    name: "Dory Fish",
    categoryId: "5",
    image: require("@/assets/images/foods/meat/Dory Fish.png"),
  },
  {
    id: "60",
    name: "Duck Meat",
    categoryId: "5",
    image: require("@/assets/images/foods/meat/Duck Meat.png"),
  },
  {
    id: "61",
    name: "Minced Pork",
    categoryId: "5",
    image: require("@/assets/images/foods/meat/Minced Pork.png"),
  },
  {
    id: "62",
    name: "Mussels",
    categoryId: "5",
    image: require("@/assets/images/foods/meat/Mussels.png"),
  },
  {
    id: "63",
    name: "Pork Belly",
    categoryId: "5",
    image: require("@/assets/images/foods/meat/Pork Belly.png"),
  },
  {
    id: "64",
    name: "Pork Collar",
    categoryId: "5",
    image: require("@/assets/images/foods/meat/Pork Collar.png"),
  },
  {
    id: "65",
    name: "Pork Slices",
    categoryId: "5",
    image: require("@/assets/images/foods/meat/Pork Slices.png"),
  },
  {
    id: "66",
    name: "Salmon",
    categoryId: "5",
    image: require("@/assets/images/foods/meat/Salmon.png"),
  },
  {
    id: "67",
    name: "Sea Bass",
    categoryId: "5",
    image: require("@/assets/images/foods/meat/Sea Bass.png"),
  },
  {
    id: "68",
    name: "Short mackerel",
    categoryId: "5",
    image: require("@/assets/images/foods/meat/Short mackerel.png"),
  },
  {
    id: "69",
    name: "Shrimp",
    categoryId: "5",
    image: require("@/assets/images/foods/meat/Shrimp.png"),
  },
  {
    id: "70",
    name: "Squid",
    categoryId: "5",
    image: require("@/assets/images/foods/meat/Squid.png"),
  },
  {
    id: "71",
    name: "Boat Noodles",
    categoryId: "12",
    image: require("@/assets/images/foods/noodles/Boat Noodles.png"),
  },
  {
    id: "72",
    name: "Dry Thai Sukiyaki",
    categoryId: "12",
    image: require("@/assets/images/foods/noodles/Dry Thai Sukiyaki.png"),
  },
  {
    id: "73",
    name: "Egg Noodles with Red Pork",
    categoryId: "12",
    image: require("@/assets/images/foods/noodles/Egg Noodles with Red Pork.png"),
  },
  {
    id: "74",
    name: "Pad Thai with Fresh Shrimp",
    categoryId: "12",
    image: require("@/assets/images/foods/noodles/Pad Thai with Fresh Shrimp.png"),
  },
  {
    id: "75",
    name: "Pork Noodles in Gravy",
    categoryId: "12",
    image: require("@/assets/images/foods/noodles/Pork Noodles in Gravy.png"),
  },
  {
    id: "76",
    name: "Rice Noodles with Fish Curry Sauce",
    categoryId: "12",
    image: require("@/assets/images/foods/noodles/Rice Noodles with Fish Curry Sauce.png"),
  },
  {
    id: "77",
    name: "Stir-fried Soy Sauce Noodles with Pork",
    categoryId: "12",
    image: require("@/assets/images/foods/noodles/Stir-fried Soy Sauce Noodles with Pork.png"),
  },
  {
    id: "78",
    name: "Stir-fried Spicy Instant Noodles with Seafood",
    categoryId: "12",
    image: require("@/assets/images/foods/noodles/Stir-fried Spicy Instant Noodles with Seafood.png"),
  },
  {
    id: "79",
    name: "Thai Sukiyaki Soup",
    categoryId: "12",
    image: require("@/assets/images/foods/noodles/Thai Sukiyaki Soup.png"),
  },
  {
    id: "80",
    name: "Tom Yum Noodles",
    categoryId: "12",
    image: require("@/assets/images/foods/noodles/Tom Yum Noodles.png"),
  },
  {
    id: "81",
    name: "Clear Soup with Tofu and Minced Pork",
    categoryId: "1",
    image: require("@/assets/images/foods/side-dish/Clear Soup with Tofu and Minced Pork.png"),
  },
  {
    id: "82",
    name: "Fried Sea Bass with Fish Sauce",
    categoryId: "1",
    image: require("@/assets/images/foods/side-dish/Fried Sea Bass with Fish Sauce.png"),
  },
  {
    id: "83",
    name: "Green Curry with Chicken",
    categoryId: "1",
    image: require("@/assets/images/foods/side-dish/Green Curry with Chicken.png"),
  },
  {
    id: "84",
    name: "Pork Panang Curry",
    categoryId: "1",
    image: require("@/assets/images/foods/side-dish/Pork Panang Curry.png"),
  },
  {
    id: "85",
    name: "Stir-fried Chicken with Cashew Nuts",
    categoryId: "1",
    image: require("@/assets/images/foods/side-dish/Stir-fried Chicken with Cashew Nuts.png"),
  },
  {
    id: "86",
    name: "Stir-fried Chinese Kale with Crispy Pork",
    categoryId: "1",
    image: require("@/assets/images/foods/side-dish/Stir-fried Chinese Kale with Crispy Pork.png"),
  },
  {
    id: "87",
    name: "Stir-fried Mixed Vegetables",
    categoryId: "1",
    image: require("@/assets/images/foods/side-dish/Stir-fried Mixed Vegetables.png"),
  },
  {
    id: "88",
    name: "Stir-fried Shrimp with Holy Basil",
    categoryId: "1",
    image: require("@/assets/images/foods/side-dish/Stir-fried Shrimp with Holy Basil.png"),
  },
  {
    id: "89",
    name: "Thai Five-spice Stewed Eggs",
    categoryId: "1",
    image: require("@/assets/images/foods/side-dish/Thai Five-spice Stewed Eggs.png"),
  },
  {
    id: "90",
    name: "Tom Yum Goong",
    categoryId: "1",
    image: require("@/assets/images/foods/side-dish/Tom Yum Goong.png"),
  },
  {
    id: "91",
    name: "Creamy Omelet with Shrimp over Rice",
    categoryId: "8",
    image: require("@/assets/images/foods/single-dish/Creamy Omelet with Shrimp over Rice.png"),
  },
  {
    id: "92",
    name: "Garlic Pork Rice",
    categoryId: "8",
    image: require("@/assets/images/foods/single-dish/Garlic Pork Rice.png"),
  },
  {
    id: "93",
    name: "Hainanese Chicken Rice",
    categoryId: "8",
    image: require("@/assets/images/foods/single-dish/Hainanese Chicken Rice.png"),
  },
  {
    id: "94",
    name: "Red Pork and Crispy Pork Rice",
    categoryId: "8",
    image: require("@/assets/images/foods/single-dish/Red Pork and Crispy Pork Rice.png"),
  },
  {
    id: "95",
    name: "Rice with Stir-fried Holy Basil Minced Pork and Fried Egg",
    categoryId: "8",
    image: require("@/assets/images/foods/single-dish/Rice with Stir-fried Holy Basil Minced Pork and Fried Egg.png"),
  },
  {
    id: "96",
    name: "Roasted Duck Rice",
    categoryId: "8",
    image: require("@/assets/images/foods/single-dish/Roasted Duck Rice.png"),
  },
  {
    id: "97",
    name: "Shrimp Fried Rice",
    categoryId: "8",
    image: require("@/assets/images/foods/single-dish/Shrimp Fried Rice.png"),
  },
  {
    id: "98",
    name: "Shrimp Paste Fried Rice",
    categoryId: "8",
    image: require("@/assets/images/foods/single-dish/Shrimp Paste Fried Rice.png"),
  },
  {
    id: "99",
    name: "Stewed Pork Leg Rice",
    categoryId: "8",
    image: require("@/assets/images/foods/single-dish/Stewed Pork Leg Rice.png"),
  },
  {
    id: "100",
    name: "Thai Chicken Biryani Rice",
    categoryId: "8",
    image: require("@/assets/images/foods/single-dish/Thai Chicken Biryani Rice.png"),
  },
  {
    id: "101",
    name: "Chicken Nuggets",
    categoryId: "2",
    image: require("@/assets/images/foods/snacks/Chicken Nuggets.png"),
  },
  {
    id: "102",
    name: "Chicken Pop",
    categoryId: "2",
    image: require("@/assets/images/foods/snacks/Chicken Pop.png"),
  },
  {
    id: "103",
    name: "French Fries",
    categoryId: "2",
    image: require("@/assets/images/foods/snacks/French Fries.png"),
  },
  {
    id: "104",
    name: "Fried Meatballs",
    categoryId: "2",
    image: require("@/assets/images/foods/snacks/Fried Meatballs.png"),
  },
  {
    id: "105",
    name: "Fried Sausages",
    categoryId: "2",
    image: require("@/assets/images/foods/snacks/Fried Sausages.png"),
  },
  {
    id: "106",
    name: "Fried Spring Rolls",
    categoryId: "2",
    image: require("@/assets/images/foods/snacks/Fried Spring Rolls.png"),
  },
  {
    id: "107",
    name: "Fried Wontons",
    categoryId: "2",
    image: require("@/assets/images/foods/snacks/Fried Wontons.png"),
  },
  {
    id: "108",
    name: "Garlic Bread",
    categoryId: "2",
    image: require("@/assets/images/foods/snacks/Garlic Bread.png"),
  },
  {
    id: "109",
    name: "Pork Satay",
    categoryId: "2",
    image: require("@/assets/images/foods/snacks/Pork Satay.png"),
  },
  {
    id: "110",
    name: "Thai Fish Cakes",
    categoryId: "2",
    image: require("@/assets/images/foods/snacks/Thai Fish Cakes.png"),
  },
  {
    id: "111",
    name: "Bamboo Shoots",
    categoryId: "7",
    image: require("@/assets/images/foods/vegetables/Bamboo Shoots.png"),
  },
  {
    id: "112",
    name: "Bell Pepper",
    categoryId: "7",
    image: require("@/assets/images/foods/vegetables/Bell Pepper.png"),
  },
  {
    id: "113",
    name: "Broccoli",
    categoryId: "7",
    image: require("@/assets/images/foods/vegetables/Broccoli.png"),
  },
  {
    id: "114",
    name: "Cabbage",
    categoryId: "7",
    image: require("@/assets/images/foods/vegetables/Cabbage.png"),
  },
  {
    id: "115",
    name: "Carrot",
    categoryId: "7",
    image: require("@/assets/images/foods/vegetables/Carrot.png"),
  },
  {
    id: "116",
    name: "Cauliflower",
    categoryId: "7",
    image: require("@/assets/images/foods/vegetables/Cauliflower.png"),
  },
  {
    id: "117",
    name: "Chinese Cabbage",
    categoryId: "7",
    image: require("@/assets/images/foods/vegetables/Chinese Cabbage.png"),
  },
  {
    id: "118",
    name: "Chinese Kale",
    categoryId: "7",
    image: require("@/assets/images/foods/vegetables/Chinese Kale.png"),
  },
  {
    id: "119",
    name: "Cucumber",
    categoryId: "7",
    image: require("@/assets/images/foods/vegetables/Cucumber.png"),
  },
  {
    id: "120",
    name: "Enoki Mushroom",
    categoryId: "7",
    image: require("@/assets/images/foods/vegetables/Enoki Mushroom.png"),
  },
  {
    id: "121",
    name: "Holy Basil",
    categoryId: "7",
    image: require("@/assets/images/foods/vegetables/Holy Basil.png"),
  },
  {
    id: "122",
    name: "Long Eggplant",
    categoryId: "7",
    image: require("@/assets/images/foods/vegetables/Long Eggplant.png"),
  },
  {
    id: "123",
    name: "Morning Glory",
    categoryId: "7",
    image: require("@/assets/images/foods/vegetables/Morning Glory.png"),
  },
  {
    id: "124",
    name: "Onion",
    categoryId: "7",
    image: require("@/assets/images/foods/vegetables/Onion.png"),
  },
  {
    id: "125",
    name: "Oyster Mushroom",
    categoryId: "7",
    image: require("@/assets/images/foods/vegetables/Oyster Mushroom.png"),
  },
  {
    id: "126",
    name: "Pumpkin",
    categoryId: "7",
    image: require("@/assets/images/foods/vegetables/Pumpkin.png"),
  },
  {
    id: "127",
    name: "Spring Onion",
    categoryId: "7",
    image: require("@/assets/images/foods/vegetables/Spring Onion.png"),
  },
  {
    id: "128",
    name: "Thai Eggplant",
    categoryId: "7",
    image: require("@/assets/images/foods/vegetables/Thai Eggplant.png"),
  },
  {
    id: "129",
    name: "Tomato",
    categoryId: "7",
    image: require("@/assets/images/foods/vegetables/Tomato.png"),
  },
  {
    id: "130",
    name: "Yardlong Bean",
    categoryId: "7",
    image: require("@/assets/images/foods/vegetables/Yardlong Bean.png"),
  },
  {
    id: "131",
    name: "Green Curry with Tofu",
    categoryId: "11",
    image: require("@/assets/images/foods/vegetarian/Green Curry with Tofu.png"),
  },
  {
    id: "132",
    name: "Spicy Mixed Mushroom Salad",
    categoryId: "11",
    image: require("@/assets/images/foods/vegetarian/Spicy Mixed Mushroom Salad.png"),
  },
  {
    id: "133",
    name: "Spicy Mushroom Larb",
    categoryId: "11",
    image: require("@/assets/images/foods/vegetarian/Spicy Mushroom Larb.png"),
  },
  {
    id: "134",
    name: "Stir-fried Tofu with Holy Basil",
    categoryId: "11",
    image: require("@/assets/images/foods/vegetarian/Stir-fried Tofu with Holy Basil.png"),
  },
  {
    id: "135",
    name: "Stir-fried Tofu with Mixed Vegetables",
    categoryId: "11",
    image: require("@/assets/images/foods/vegetarian/Stir-fried Tofu with Mixed Vegetables.png"),
  },
  {
    id: "136",
    name: "Teriyaki Mushroom Rice Bowl",
    categoryId: "11",
    image: require("@/assets/images/foods/vegetarian/Teriyaki Mushroom Rice Bowl.png"),
  },
  {
    id: "137",
    name: "Vegetable Curry Rice",
    categoryId: "11",
    image: require("@/assets/images/foods/vegetarian/Vegetable Curry Rice.png"),
  },
  {
    id: "138",
    name: "Vegetable Fried Rice",
    categoryId: "11",
    image: require("@/assets/images/foods/vegetarian/Vegetable Fried Rice.png"),
  },
  {
    id: "139",
    name: "Vegetable Sukiyaki",
    categoryId: "11",
    image: require("@/assets/images/foods/vegetarian/Vegetable Sukiyaki.png"),
  },
  {
    id: "140",
    name: "Vegetarian Pad Thai",
    categoryId: "11",
    image: require("@/assets/images/foods/vegetarian/Vegetarian Pad Thai.png"),
  },
];
