SET local check_function_bodies = off;

CREATE TABLE "public"."categories" (
  "id"         bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name"       character varying(100)   NOT NULL,
  "created_at" timestamp with time zone DEFAULT now(),
  CONSTRAINT "categories_name_key" UNIQUE (name),
  CONSTRAINT "categories_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."categories"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."foods" (
  "id"          bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name"        character varying(200)   NOT NULL,
  "image_url"   text,
  "category_id" bigint                   NOT NULL,
  "created_at"  timestamp with time zone DEFAULT now(),
  CONSTRAINT "foods_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."foods"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."ingredient_categories" (
  "id"         bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name"       character varying(100)   NOT NULL,
  "created_at" timestamp with time zone DEFAULT now(),
  CONSTRAINT "ingredient_categories_name_key" UNIQUE (name),
  CONSTRAINT "ingredient_categories_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."ingredient_categories"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."ingredients" (
  "id"          bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name"        character varying(200)   NOT NULL,
  "image_url"   text,
  "category_id" bigint                   NOT NULL,
  "created_at"  timestamp with time zone DEFAULT now(),
  CONSTRAINT "ingredients_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."ingredients"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."post_categories" (
  "post_id"     bigint NOT NULL,
  "category_id" bigint NOT NULL,
  CONSTRAINT "post_categories_pkey" PRIMARY KEY (post_id, category_id)
);

ALTER TABLE "public"."post_categories"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."posts" (
  "id"             bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "user_id"        uuid                     NOT NULL,
  "food_name"      character varying(200)   NOT NULL,
  "description"    text,
  "restaurant_url" text,
  "image_url"      text,
  "created_at"     timestamp with time zone DEFAULT now(),
  "updated_at"     timestamp with time zone DEFAULT now(),
  CONSTRAINT "posts_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."posts"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."profiles" (
  "id"           uuid                     NOT NULL,
  "username"     character varying(50)    NOT NULL,
  "display_name" character varying(100),
  "bio"          text,
  "avatar_url"   text,
  "created_at"   timestamp with time zone DEFAULT now(),
  "updated_at"   timestamp with time zone DEFAULT now(),
  CONSTRAINT "profiles_display_name_unique" UNIQUE (display_name),
  CONSTRAINT "profiles_pkey" PRIMARY KEY (id),
  CONSTRAINT "profiles_username_key" UNIQUE (username),
  CONSTRAINT "username_format_check" CHECK (((username)::text ~ '^[a-z]+$'::text))
);

ALTER TABLE "public"."profiles"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."saved_posts" (
  "user_id"    uuid                     NOT NULL,
  "post_id"    bigint                   NOT NULL,
  "created_at" timestamp with time zone DEFAULT now(),
  CONSTRAINT "saved_posts_pkey" PRIMARY KEY (user_id, post_id)
);

ALTER TABLE "public"."saved_posts"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."search_history" (
  "id"         bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "user_id"    uuid                     NOT NULL,
  "query"      character varying(255)   NOT NULL,
  "created_at" timestamp with time zone DEFAULT now(),
  CONSTRAINT "search_history_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."search_history"
  ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.handle_new_user()
  RETURNS TRIGGER
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO 'public'
  AS $function$
DECLARE
    display_name_value text;
    username_base text;
    username_value text;
    suffix text;
BEGIN
    -- รับ Display Name จากข้อมูลที่ส่งมาพร้อม Supabase Auth
    display_name_value :=
        NEW.raw_user_meta_data ->> 'display_name';

    -- ตัดช่องว่างหน้า-หลัง
    display_name_value :=
        trim(display_name_value);

    /*
      สร้าง username จาก email

      เช่น
      supasin@gmail.com
      → supasin

      supasin.test@gmail.com
      → supasin
    */
    username_base :=
        split_part(
            split_part(lower(NEW.email), '@', 1),
            '.',
            1
        );

    -- เอาเฉพาะ a-z
    username_base :=
        regexp_replace(
            username_base,
            '[^a-z]',
            '',
            'g'
        );

    /*
      ถ้าสร้างจาก email ไม่ได้
      ให้สร้างชื่อภาษาอังกฤษใหม่
    */
    IF username_base = '' THEN
        username_base :=
            'user' ||
            substr(
                md5(random()::text),
                1,
                6
            );
    END IF;

    username_value := username_base;

    /*
      ถ้า username ซ้ำ
      เพิ่มตัวอักษรภาษาอังกฤษท้ายชื่อ
    */
    WHILE EXISTS (
        SELECT 1
        FROM public.profiles
        WHERE username = username_value
    )
    LOOP
        suffix :=
            substr(
                md5(random()::text),
                1,
                4
            );

        username_value :=
            username_base || suffix;
    END LOOP;

    -- สร้าง profile
    INSERT INTO public.profiles (
        id,
        username,
        display_name
    )
    VALUES (
        NEW.id,
        username_value,
        display_name_value
    );

    RETURN NEW;
END;
$function$;

ALTER TABLE "public"."foods"
  ADD CONSTRAINT "foods_category_id_fkey" FOREIGN KEY (category_id) REFERENCES public.categories(id);

ALTER TABLE "public"."ingredients"
  ADD CONSTRAINT "ingredients_category_id_fkey" FOREIGN KEY (category_id) REFERENCES public.ingredient_categories(id);

ALTER TABLE "public"."post_categories"
  ADD CONSTRAINT "post_categories_category_id_fkey" FOREIGN KEY (category_id) REFERENCES public.categories(id) ON DELETE CASCADE;

ALTER TABLE "public"."post_categories"
  ADD CONSTRAINT "post_categories_post_id_fkey" FOREIGN KEY (post_id) REFERENCES public.posts(id) ON DELETE CASCADE;

ALTER TABLE "public"."posts"
  ADD CONSTRAINT "posts_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."profiles"
  ADD CONSTRAINT "profiles_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."saved_posts"
  ADD CONSTRAINT "saved_posts_post_id_fkey" FOREIGN KEY (post_id) REFERENCES public.posts(id) ON DELETE CASCADE;

ALTER TABLE "public"."saved_posts"
  ADD CONSTRAINT "saved_posts_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."search_history"
  ADD CONSTRAINT "search_history_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

CREATE INDEX idx_foods_category_id ON public.foods USING btree (category_id);

CREATE INDEX idx_ingredients_category_id ON public.ingredients USING btree (category_id);

CREATE INDEX idx_post_categories_category_id ON public.post_categories USING btree (category_id);

CREATE INDEX idx_posts_created_at ON public.posts USING btree (created_at DESC);

CREATE INDEX idx_posts_user_id ON public.posts USING btree (user_id);

CREATE INDEX idx_saved_posts_post_id ON public.saved_posts USING btree (post_id);

CREATE INDEX idx_search_history_user_id ON public.search_history USING btree (user_id);

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_new_user();

CREATE POLICY "Anyone can view categories" ON "public"."categories"
  FOR SELECT
  TO PUBLIC
  USING (true);

CREATE POLICY "Anyone can view foods" ON "public"."foods"
  FOR SELECT
  TO PUBLIC
  USING (true);

CREATE POLICY "Anyone can view ingredient categories" ON "public"."ingredient_categories"
  FOR SELECT
  TO PUBLIC
  USING (true);

CREATE POLICY "Anyone can view ingredients" ON "public"."ingredients"
  FOR SELECT
  TO PUBLIC
  USING (true);

CREATE POLICY "Anyone can view post categories" ON "public"."post_categories"
  FOR SELECT
  TO PUBLIC
  USING (true);

CREATE POLICY "Users can add categories to their own posts" ON "public"."post_categories"
  FOR INSERT
  TO "authenticated"
  WITH CHECK ((EXISTS ( SELECT 1
   FROM public.posts
  WHERE ((posts.id = post_categories.post_id) AND (posts.user_id = auth.uid())))));

CREATE POLICY "Users can remove categories from their own posts" ON "public"."post_categories"
  FOR DELETE
  TO "authenticated"
  USING ((EXISTS ( SELECT 1
   FROM public.posts
  WHERE ((posts.id = post_categories.post_id) AND (posts.user_id = auth.uid())))));

CREATE POLICY "Anyone can view posts" ON "public"."posts"
  FOR SELECT
  TO PUBLIC
  USING (true);

CREATE POLICY "Authenticated users can create posts" ON "public"."posts"
  FOR INSERT
  TO "authenticated"
  WITH CHECK ((auth.uid() = user_id));

CREATE POLICY "Users can delete their own posts" ON "public"."posts"
  FOR DELETE
  TO "authenticated"
  USING ((auth.uid() = user_id));

CREATE POLICY "Users can update their own posts" ON "public"."posts"
  FOR UPDATE
  TO "authenticated"
  USING ((auth.uid() = user_id))
  WITH CHECK ((auth.uid() = user_id));

CREATE POLICY "Anyone can view profiles" ON "public"."profiles"
  FOR SELECT
  TO PUBLIC
  USING (true);

CREATE POLICY "Users can create their own profile" ON "public"."profiles"
  FOR INSERT
  TO PUBLIC
  WITH CHECK ((auth.uid() = id));

CREATE POLICY "Users can update their own profile" ON "public"."profiles"
  FOR UPDATE
  TO PUBLIC
  USING ((auth.uid() = id))
  WITH CHECK ((auth.uid() = id));

CREATE POLICY "Users can save posts" ON "public"."saved_posts"
  FOR INSERT
  TO "authenticated"
  WITH CHECK ((auth.uid() = user_id));

CREATE POLICY "Users can unsave posts" ON "public"."saved_posts"
  FOR DELETE
  TO "authenticated"
  USING ((auth.uid() = user_id));

CREATE POLICY "Users can view their own saved posts" ON "public"."saved_posts"
  FOR SELECT
  TO "authenticated"
  USING ((auth.uid() = user_id));

CREATE POLICY "Users can create their own search history" ON "public"."search_history"
  FOR INSERT
  TO "authenticated"
  WITH CHECK ((auth.uid() = user_id));

CREATE POLICY "Users can delete their own search history" ON "public"."search_history"
  FOR DELETE
  TO "authenticated"
  USING ((auth.uid() = user_id));

CREATE POLICY "Users can view their own search history" ON "public"."search_history"
  FOR SELECT
  TO "authenticated"
  USING ((auth.uid() = user_id));

CREATE POLICY "Anyone can view avatars" ON "storage"."objects"
  FOR SELECT
  TO PUBLIC
  USING ((bucket_id = 'avatars'::text));

CREATE POLICY "Anyone can view post images" ON "storage"."objects"
  FOR SELECT
  TO PUBLIC
  USING ((bucket_id = 'posts'::text));

CREATE POLICY "Users can delete their own avatars" ON "storage"."objects"
  FOR DELETE
  TO "authenticated"
  USING (((bucket_id = 'avatars'::text) AND ((storage.foldername(name))[1] = ( SELECT (auth.uid())::text AS uid))));

CREATE POLICY "Users can delete their own post images" ON "storage"."objects"
  FOR DELETE
  TO "authenticated"
  USING (((bucket_id = 'posts'::text) AND ((storage.foldername(name))[1] = ( SELECT (auth.uid())::text AS uid))));

CREATE POLICY "Users can update their own avatars" ON "storage"."objects"
  FOR UPDATE
  TO "authenticated"
  USING (((bucket_id = 'avatars'::text) AND ((storage.foldername(name))[1] = ( SELECT (auth.uid())::text AS uid))))
  WITH CHECK (((bucket_id = 'avatars'::text) AND ((storage.foldername(name))[1] = ( SELECT (auth.uid())::text AS uid))));

CREATE POLICY "Users can update their own post images" ON "storage"."objects"
  FOR UPDATE
  TO "authenticated"
  USING (((bucket_id = 'posts'::text) AND ((storage.foldername(name))[1] = ( SELECT (auth.uid())::text AS uid))))
  WITH CHECK (((bucket_id = 'posts'::text) AND ((storage.foldername(name))[1] = ( SELECT (auth.uid())::text AS uid))));

CREATE POLICY "Users can upload their own avatars" ON "storage"."objects"
  FOR INSERT
  TO "authenticated"
  WITH CHECK (((bucket_id = 'avatars'::text) AND ((storage.foldername(name))[1] = ( SELECT (auth.uid())::text AS uid))));

CREATE POLICY "Users can upload their own post images" ON "storage"."objects"
  FOR INSERT
  TO "authenticated"
  WITH CHECK (((bucket_id = 'posts'::text) AND ((storage.foldername(name))[1] = ( SELECT (auth.uid())::text AS uid))));

GRANT EXECUTE ON FUNCTION "public"."handle_new_user"() TO PUBLIC, "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."categories" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."foods" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."ingredient_categories" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."ingredients" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."post_categories" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."posts" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."profiles" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."saved_posts" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."search_history" TO "anon", "authenticated", "postgres", "service_role";

